### ISSUE TITLE
Simple CMS: Can't create a new page unless the name starts with /

### ISSUE THREAD

**Issue by frabrunelle** [beakerbrowser/beaker.dev#1]
Hey Paul! I noticed a minor issue with the Simple CMS template. When I click New and enter a name for a new page, it doesn't create the new page unless I make sure to add a slash first (e.g."/new-page" works but not "new-page"). In the console it says:

> Uncaught (in promise) Error: Uncaught InvalidURLError: Hostname is not a valid hash

Here's the relevant code:

```js
async function onNew (e) {
  var path = prompt('Enter the name of your new page')
  if (!path) return
  if (!path.endsWith('.html')) path += '.html'
  await beaker.hyperdrive.writeFile(path, `<h1>${path}</h1>`)
  location.pathname = path
}
```

Is this an issue with the `beaker.hyperdrive.writeFile` API? Or should the Simple CMS template be changed to automatically prepend a slash if one is not present? (or convert the name to a hyper:// URL)

**Comment by pfrazee** [comment]
Thanks for the heads up, I'll check into that

**Comment by pfrazee** [comment]
Fixed. Will deploy in a few
